services:
  dev:
    image: chaos-dev

    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /workspace

    volumes:
      - type: bind
        source: .
        target: /workspace

    stdin_open: true
    tty: true
