name: Check builds succeed

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Docker image
        run: docker compose build

      - name: Build kernel
        run: docker compose run --rm -T dev make

      - name: Build documentation
        run: docker compose run --rm -T dev make docs
